# ~/.circleci/config.yml
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14.2
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install
      - run: echo `module.exports = { Pass_Add : {Git_Id : "",Git_Sec : "",session_Secret: "",Twi_Id:"",Twi_Sec:""},this_pages_Address: '',Git_collback_Address:"",Twi_collback_Address:""};` > config.js

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: mkdir junit
      - run:
          command: node_modules/.bin/mocha test --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: ./junit/test-results.xml
          when: always
      - store_test_results:
          path: ./junit
      - store_artifacts:
          path: ./junit